### ISSUE TITLE
test

### ISSUE THREAD

**Issue by sils** [sils1297/git-tutorial-test-commits#1]
@coafile-master

**Comment by coafile-master** [comment]
Greetings! I'm the coafile bot and I'm here to get your coafile ready. Sit Tight!

**Comment by coafile-master** [comment]
```# Generated by coala-quickstart on 03 Aug 2017.
[default]
bears = FilenameBear, LineCountBear, InvalidLinkBear
files = **.md
[markdown]
bears = MarkdownBear, DuplicateFileBear, LicenseCheckBear, KeywordBear, LineLengthBear, coalaBear, SpaceConsistencyBear
files = **.md
```

**Comment by coafile-master** [comment]
coafile creation process Successful! :tada: :tada: :tada:


 Next Steps: 

 Step 1: Merge the Pull Request https://github.com/sils/git-tutorial-test-commits/pull/2 having the .coafile.
 Step 2: Turn on [GitMate](https://gitmate.io) Integration on this repository.
 Step 3: Turn on code analysis for automated code reviews on your PRs.

 Happy Linting! :tada:
